/** Route reachability registry + sidebar/reports href lists. */

import type { RouteEntryKind } from "@/lib/nav-section-types";

/** Routes registered in appRoutes but hidden from sidebar (reachable via tabs/cards). */
export const SIDEBAR_HIDDEN_HREFS = new Set([
  "/expenses",
  "/uploads",
  "/close-day",
  "/cards",
  "/payables",
  "/receivables",
  "/review/bank",
  "/review/sales",
  "/review/receipts",
  "/review/invoices",
  "/review/expenses",
  "/review/delivery",
  "/review/manual-journals",
  "/banking/transfers",
  "/banking/cash",
  "/banking/banks",
  "/banking/cards",
  "/banking/fx",
  "/delivery/reports",
  "/delivery/settlements",
  "/delivery/platforms",
  "/accounting/manual-journals",
  "/onboarding/opening-balances",
]);

export const REPORTS_CARD_HREFS = [
  "/reports/profit-and-loss",
  "/reports/balance-sheet",
  "/reports/cash-flow",
  "/reports/ledger",
  "/reports/expense-register",
  "/reports/cash-book",
  "/reports/bank-reconciliation",
  "/reports/month-close",
  "/reports/kdv-input",
  "/reports/delivery-sales",
  "/reports/period-comparison",
] as const;

/** Static page routes — used by reachability guard test. */
/** Old bookmark URLs — redirect to directories or dashboard. */
export const LEGACY_BALANCE_REDIRECTS: Record<string, string> = {
  "/payables": "/suppliers",
  "/receivables": "/customers",
  "/balances": "/",
  "/balances/suppliers": "/suppliers",
  "/balances/customers": "/customers",
  "/balances/staff": "/staff",
  "/balances/partners": "/partners",
  "/balances/cash": "/banking",
};

export const REGISTERED_PAGE_ROUTES: { pattern: string; kind: RouteEntryKind }[] =
  [
    { pattern: "/", kind: "sidebar" },
    { pattern: "/record", kind: "sidebar" },
    { pattern: "/review", kind: "sidebar" },
    { pattern: "/review/bank", kind: "tab" },
    { pattern: "/review/sales", kind: "tab" },
    { pattern: "/review/receipts", kind: "tab" },
    { pattern: "/review/invoices", kind: "tab" },
    { pattern: "/review/expenses", kind: "tab" },
    { pattern: "/review/delivery", kind: "tab" },
    { pattern: "/review/posted", kind: "redirect" },
    { pattern: "/review/manual-journals", kind: "tab" },
    { pattern: "/balances", kind: "redirect" },
    { pattern: "/balances/suppliers", kind: "redirect" },
    { pattern: "/balances/customers", kind: "redirect" },
    { pattern: "/balances/staff", kind: "redirect" },
    { pattern: "/balances/partners", kind: "redirect" },
    { pattern: "/balances/cash", kind: "redirect" },
    { pattern: "/sales", kind: "tab" },
    { pattern: "/sales/[id]", kind: "drill-down" },
    { pattern: "/cards", kind: "tab" },
    { pattern: "/close-day", kind: "redirect" },
    { pattern: "/delivery", kind: "sidebar" },
    { pattern: "/delivery/platforms", kind: "tab" },
    { pattern: "/delivery/reports", kind: "tab" },
    { pattern: "/delivery/reports/[id]", kind: "drill-down" },
    { pattern: "/delivery/settlements", kind: "tab" },
    { pattern: "/expenses", kind: "redirect" },
    { pattern: "/expenses/items", kind: "redirect" },
    { pattern: "/uploads", kind: "redirect" },
    { pattern: "/suppliers", kind: "tab" },
    { pattern: "/suppliers/[id]", kind: "drill-down" },
    { pattern: "/payables", kind: "redirect" },
    { pattern: "/staff", kind: "tab" },
    { pattern: "/staff/[id]", kind: "drill-down" },
    { pattern: "/partners", kind: "tab" },
    { pattern: "/partners/[id]", kind: "drill-down" },
    { pattern: "/customers", kind: "tab" },
    { pattern: "/customers/[id]", kind: "drill-down" },
    { pattern: "/customers/group-menus", kind: "tab" },
    { pattern: "/customers/dishes", kind: "tab" },
    { pattern: "/customers/group-menus/[id]", kind: "drill-down" },
    { pattern: "/customers/group-sales", kind: "tab" },
    { pattern: "/customers/group-sales/[id]", kind: "drill-down" },
    { pattern: "/receivables", kind: "redirect" },
    { pattern: "/banking", kind: "tab" },
    { pattern: "/banking/banks", kind: "page" },
    { pattern: "/banking/cards", kind: "page" },
    { pattern: "/banking/fx", kind: "page" },
    { pattern: "/banking/review", kind: "redirect" },
    { pattern: "/banking/transfers", kind: "tab" },
    { pattern: "/banking/cash", kind: "tab" },
    { pattern: "/banking/accounts/[id]", kind: "drill-down" },
    { pattern: "/banking/accounts/[id]/import", kind: "drill-down" },
    { pattern: "/banking/statements/[id]", kind: "drill-down" },
    { pattern: "/banking/fx/[id]", kind: "drill-down" },
    { pattern: "/reports", kind: "sidebar" },
    { pattern: "/reports/profit-and-loss", kind: "reports-card" },
    { pattern: "/reports/balance-sheet", kind: "reports-card" },
    { pattern: "/reports/cash-flow", kind: "reports-card" },
    { pattern: "/reports/expense-register", kind: "reports-card" },
    { pattern: "/reports/cash-book", kind: "reports-card" },
    { pattern: "/reports/bank-reconciliation", kind: "reports-card" },
    { pattern: "/reports/month-close", kind: "reports-card" },
    { pattern: "/reports/kdv-input", kind: "reports-card" },
    { pattern: "/reports/delivery-sales", kind: "reports-card" },
    { pattern: "/reports/period-comparison", kind: "reports-card" },
    { pattern: "/reports/ledger", kind: "reports-card" },
    { pattern: "/accounting/manual-journals", kind: "redirect" },
    { pattern: "/setup", kind: "redirect" },
    { pattern: "/setup/restaurant", kind: "redirect" },
    { pattern: "/setup/opening-balances", kind: "redirect" },
    { pattern: "/setup/members", kind: "redirect" },
    { pattern: "/setup/expense-items", kind: "redirect" },
    { pattern: "/setup/delivery-platforms", kind: "redirect" },
    { pattern: "/setup/accounts", kind: "redirect" },
    { pattern: "/setup/accountant", kind: "redirect" },
    { pattern: "/setup/backups", kind: "redirect" },
    { pattern: "/settings", kind: "redirect" },
    { pattern: "/settings/entity", kind: "redirect" },
    { pattern: "/settings/opening-balances", kind: "redirect" },
    { pattern: "/settings/members", kind: "redirect" },
    { pattern: "/settings/expense-items", kind: "redirect" },
    { pattern: "/settings/restaurant", kind: "page" },
    { pattern: "/settings/profile", kind: "page" },
    { pattern: "/onboarding/opening-balances", kind: "page" },
    { pattern: "/review/receipts/[id]", kind: "drill-down" },
    { pattern: "/review/invoices/[id]", kind: "drill-down" },
    { pattern: "/sign-in/[[...sign-in]]", kind: "auth" },
    { pattern: "/sign-up/[[...sign-up]]", kind: "auth" },
  ];
